### ISSUE TITLE
Repeated daily email alert

### ISSUE THREAD

**Issue by diego-amazonia** [movestore/Email-Alert#6]
I've created a workflow to receive daily email alerts when the battery voltage is below 3.6V, however the email text seems to have stayed "stored".

![image](https://github.com/movestore/Email-Alert/assets/144258357/3c7ac990-3720-4411-94c7-a03429e56f2c)

So what seems to be happening is that once a tag drops below 3.6V, the app created a file with the information required. But now that the tag seems to be off and there's no more tags with low battery in the last days, the previous file gets re-sent daily instead of getting deleted.

**Comment by andreakoelzsch** [comment]
THanks for pointing this out @diego-amazonia. For solving this issue, I need to go to the backbone, which might take a few weeks to get the system developer to look at it. Please keep with me, I will let you know. Best, Andrea

**Comment by diego-amazonia** [comment]
Hi Andrea, thanks for the reply. I email Ashley of MoveApps too, as it may be a good feature for the scheduling system itself, being able to clear the created files before each run? I've no rush 🙌

**Comment by andreakoelzsch** [comment]
Hi @diego-amazonia , please would you have a look again if the error is now solved? We have updated the system that all artifacts are deleted at new workflow runs. Thanks for your help in improving the system! Best, Andrea

**Comment by diego-amazonia** [comment]
Hi Andrea! I'll continue to keep an eye on the alert. Lately I haven't received any scheduled emails from it even if the conditions are met, and the workflow runs. I did receive an alert from another weekly scheduled workflow, though. 

On that note, I have noticed the stored settings in the morning report I run are not saved. This happened only recently, not sure if they are related. If I keep getting that error I'll submit another issue.

Thanks for checking this out!

**Comment by andreakoelzsch** [comment]
Thanks for the news Diego! If you are not getting Workflow Email it might be because your Quota has run out. Did you check for that? In each Email that you get it is stating how many Emails you will still get before having to renew the Quota (which can easily be done with a link from the Email). About the settings save in the Morning Report, we will have a look. Thanks! Best, Andrea
